fixing and integrating installation scripts
adding https configuration

diff --git a/bin/create-nimbus-home b/bin/create-nimbus-home
--- a/bin/create-nimbus-home
+++ b/bin/create-nimbus-home
@@ -72,6 +72,15 @@ if [ ! -d $NIMBUS_HOME ]; then
     fi
 fi
 
+echo "Installing cumulus..."
+${NIMBUS_SRC}/cumulus/install.sh $NIMBUS_HOME/cumulus
+if [ $? -ne 0 ]; then
+    echo "Failed to install cumulus"
+    exit 1
+fi
+source $NIMBUS_HOME/cumulus/env.sh
+
+
 echo "Deploying skeleton directory structure.."
 cp -fr $NIMBUS_SRC/home/* $NIMBUS_HOME/
 if [ $? -ne 0 ]; then
