Cleaned up install script output.
Removed the .sh extensions.

diff --git a/bin/create-nimbus-home b/bin/create-nimbus-home
--- a/bin/create-nimbus-home
+++ b/bin/create-nimbus-home
@@ -27,6 +27,32 @@ if [ "X$1" == "X" ]; then
     exit 1
 fi
 
+echo ""
+echo "-----------------------------------------------------------------"
+echo " Preparing Nimbus installation directory"
+echo "-----------------------------------------------------------------"
+echo ""
+# first ensure we have a GT tarball. Most likely it has been bundled with
+# the Nimbus installer.
+if [ ! -f $TMPDIR/$CONTAINER_TARNAME ]; then
+    echo "Downloading service container.."
+    echo ""
+    wget -c -O $TMPDIR/$CONTAINER_TARNAME $CONTAINER_URL
+
+    if [ $? -ne 0 ]; then
+    echo ""
+        echo "Failed to download container tarball from: $CONTAINER_URL"
+        echo ""
+        echo "If you are unable to access the Internet, please retrieve this"
+        echo "file by other means and place it in $TMPDIR/." 
+        echo "Then rerun this script."
+
+        rm -f $TMPDIR/$CONTAINER_TARNAME
+
+        exit 1
+    fi
+fi
+
 NIMBUS_HOME=$1
 
 if [ ! -d $NIMBUS_HOME ]; then
@@ -34,7 +60,6 @@ if [ ! -d $NIMBUS_HOME ]; then
     
     if [ -d $PARENT_DIR ]; then
         
-        echo "Creating destination directory: $NIMBUS_HOME"
         mkdir $NIMBUS_HOME
 
         if [ $? -ne 0 ]; then
@@ -64,21 +89,12 @@ fi
 CONTAINER_DIR="$NIMBUS_HOME/$CONTAINER_DIRNAME"
 if [ ! -d $CONTAINER_DIR ]; then
 
-    echo "Downloading and installing service container.."
-
-    # fetch GT container if it doesn't already exist
-    if [ ! -f $TMPDIR/$CONTAINER_TARNAME ]; then
-        wget -c -O $TMPDIR/$CONTAINER_TARNAME $CONTAINER_URL
-
-        if [ $? -ne 0 ]; then
-            echo "Failed to download container tarball"
-            exit 1
-        fi
-    fi
+    echo "Installing service container.."
 
     tar xzf $TMPDIR/$CONTAINER_TARNAME -C $TMPDIR
     if [ $? -ne 0 ]; then
-        echo "Failed to expand Nimbus tarball"
+        echo "Failed to expand container tarball: $TMPDIR/$CONTAINER_TARNAME"
+        echo "If this file is corrupted, you may delete it and rerun this script to download a new one."
         exit 1
     fi
 
@@ -91,7 +107,10 @@ else
     echo "Service container already exists at $CONTAINER_DIR"
 fi
 
-echo "Building and installing Nimbus to service container.."
+echo ""
+echo "-----------------------------------------------------------------"
+echo " Building and installing Nimbus services"
+echo "-----------------------------------------------------------------"
 
 GLOBUS_LOCATION=$CONTAINER_DIR
 export GLOBUS_LOCATION
@@ -101,3 +120,5 @@ if [ $? -ne 0 ]; then
     echo "Build and install FAILED!"
     exit 1
 fi
+
+echo ""
